name: Publish to npm

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm run test:ci

    - name: Build
      run: npm run build

    - name: Get tag version
      run: echo ::set-output name=tag_version::$(echo $GITHUB_REF | sed 's/refs\/tags\///')

    - name: Publish to npm
      run: npm publish --access public --tag ${{ steps.get_tag_version.outputs.tag_version }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
